version: "3"

networks:
  mysqlNET:
  desafioapiNET:

volumes:
  LocalDatabase:

services:

  mysql:
    image: "mysql:5.7"
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - LocalDatabase:/var/lib/mysql
    networks:
      - mysqlNET
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
      - bind-address:0.0.0.0

  desafioapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafioapi
    networks:
      - mysqlNET
      - desafioapiNET
    ports:
      - 5000:80
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql
